#!/bin/bash
# scripts/interpretability/submit_pipeline.sh
# ============================================
# Master submission script for the Boltz-2 interpretability pipeline.
# Submits four SLURM job stages with dependency chaining.
#
# Usage
# -----
#   bash scripts/interpretability/submit_pipeline.sh \
#       --manifest       manifest.tsv           \
#       --checkpoint     ~/.boltz/boltz2_aff.ckpt \
#       --cached_dir     cached/                \
#       --results_dir    results/               \
#       [--partition_gpu gpu                  ] \
#       [--partition_cpu cpu                  ] \
#       [--account       my_slurm_account     ] \
#       [--conda_env     boltz_env            ] \
#       [--max_concurrent 8                   ] \
#       [--skip_cache                         ] \
#       [--run_patch     head_ablation        ] \
#       [--reference_complex COMPLEX_NAME     ] \
#       [--displacements 0.5,1.0,1.5,2.0     ] \
#       [--n_directions  8                    ] \
#       [--msa_directory /path/to/msa         ]
#
# Manifest format (TSV generated by make_manifest.py)
# ----
#   complex_name  receptor_pdb  mol2_file  ligand_name  dataset_type  pIC50
#
# Stages
# ------
#   01_cache    : Affinity-rescoring pipeline per complex (trunk +
#                 affinity head, NO diffusion). Injects PDB/MOL2
#                 coordinates. Saves .pt files.  (GPU, ~30min per complex)
#   02_analyze  : Logit-lens + SVD analysis per complex.
#                 (CPU, ~1h per complex)
#   03_patch    : Causal patching experiments per complex.
#                 (CPU, ~2h per complex; optional)
#   04_aggregate: Aggregate all CSVs → summary files.
#                 (CPU, ~30min; single job)
#
# If --skip_cache is set, jobs start from stage 02 (assumes .pt files exist).
# If --run_patch  is set, stage 03 is inserted between 02 and 04.

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
MANIFEST=""
CHECKPOINT=""
CACHED_DIR=""
RESULTS_DIR=""
PARTITION_GPU="maom-h200"
PARTITION_CPU="standard"
ACCOUNT=""
CONDA_ENV="boltz_env"
MAX_CONCURRENT=8
SKIP_CACHE=0
RUN_PATCH=""
REFERENCE_COMPLEX=""
DISPLACEMENTS="0.5,1.0,1.5,2.0"
N_DIRECTIONS=8
MSA_DIRECTORY=""

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --manifest)          MANIFEST="$2";          shift ;;
        --checkpoint)        CHECKPOINT="$2";        shift ;;
        --cached_dir)        CACHED_DIR="$2";        shift ;;
        --results_dir)       RESULTS_DIR="$2";       shift ;;
        --partition_gpu)     PARTITION_GPU="$2";     shift ;;
        --partition_cpu)     PARTITION_CPU="$2";     shift ;;
        --account)           ACCOUNT="$2";           shift ;;
        --conda_env)         CONDA_ENV="$2";         shift ;;
        --max_concurrent)    MAX_CONCURRENT="$2";    shift ;;
        --skip_cache)        SKIP_CACHE=1            ;;
        --run_patch)         RUN_PATCH="$2";         shift ;;
        --reference_complex) REFERENCE_COMPLEX="$2"; shift ;;
        --displacements)     DISPLACEMENTS="$2";     shift ;;
        --n_directions)      N_DIRECTIONS="$2";      shift ;;
        --msa_directory)     MSA_DIRECTORY="$2";      shift ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
    shift
done

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
[[ -z "$MANIFEST"   ]] && { echo "ERROR: --manifest is required";   exit 1; }
[[ -z "$CHECKPOINT" ]] && { echo "ERROR: --checkpoint is required"; exit 1; }
[[ -z "$CACHED_DIR" ]] && { echo "ERROR: --cached_dir is required"; exit 1; }
[[ -z "$RESULTS_DIR" ]] && { echo "ERROR: --results_dir is required"; exit 1; }
[[ -f "$MANIFEST"   ]] || { echo "ERROR: manifest not found: $MANIFEST"; exit 1; }

MANIFEST=$(realpath "$MANIFEST")
CHECKPOINT=$(realpath "$CHECKPOINT")
CACHED_DIR=$(realpath "$CACHED_DIR")
RESULTS_DIR=$(realpath "$RESULTS_DIR")

# Project root = two levels up from this script.
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SLURM_DIR="$PROJECT_ROOT/scripts/interpretability/slurm"

# Count complexes (minus header line).
N_COMPLEXES=$(tail -n +2 "$MANIFEST" | grep -c .)
if [[ "$N_COMPLEXES" -eq 0 ]]; then
    echo "ERROR: manifest is empty (no rows below header)"
    exit 1
fi
ARRAY_SPEC="0-$((N_COMPLEXES - 1))%${MAX_CONCURRENT}"

mkdir -p logs

# ---------------------------------------------------------------------------
# Common --export string passed to every SLURM job
# ---------------------------------------------------------------------------
COMMON_EXPORT=(
    "ALL"
    "MANIFEST=$MANIFEST"
    "CHECKPOINT=$CHECKPOINT"
    "CACHED_DIR=$CACHED_DIR"
    "RESULTS_DIR=$RESULTS_DIR"
    "PROJECT_ROOT=$PROJECT_ROOT"
    "CONDA_ENV=$CONDA_ENV"
)
[[ -n "$MSA_DIRECTORY" ]] && COMMON_EXPORT+=("MSA_DIRECTORY=$MSA_DIRECTORY")
EXPORT_STR=$(IFS=','; echo "${COMMON_EXPORT[*]}")

# Optional account flag
ACCOUNT_FLAG=()
[[ -n "$ACCOUNT" ]] && ACCOUNT_FLAG=(--account="$ACCOUNT")

echo "======================================================="
echo "Manifest    : $MANIFEST ($N_COMPLEXES complexes)"
echo "Checkpoint  : $CHECKPOINT"
echo "Cached dir  : $CACHED_DIR"
echo "Results dir : $RESULTS_DIR"
echo "Array spec  : $ARRAY_SPEC"
echo "======================================================="

# ---------------------------------------------------------------------------
# Stage 1: Cache inputs (GPU)
# ---------------------------------------------------------------------------
PREV_JOB_IDS=""

if [[ "$SKIP_CACHE" -eq 0 ]]; then
    JOB1=$(sbatch \
        --parsable \
        --array="$ARRAY_SPEC" \
        --partition="$PARTITION_GPU" \
        "${ACCOUNT_FLAG[@]}" \
        --export="${EXPORT_STR},DEVICE=cuda" \
        "$SLURM_DIR/01_cache.slurm")
    echo "Submitted 01_cache  → job array $JOB1"
    PREV_JOB_IDS="$JOB1"
else
    echo "Skipping 01_cache (--skip_cache set)"
fi

# ---------------------------------------------------------------------------
# Stage 2: Logit-lens + SVD analysis (CPU)
# ---------------------------------------------------------------------------
DEP2=()
[[ -n "$PREV_JOB_IDS" ]] && DEP2=(--dependency="afterok:$PREV_JOB_IDS")

JOB2=$(sbatch \
    --parsable \
    --array="$ARRAY_SPEC" \
    --partition="$PARTITION_CPU" \
    "${ACCOUNT_FLAG[@]}" \
    "${DEP2[@]}" \
    --export="$EXPORT_STR" \
    "$SLURM_DIR/02_analyze.slurm")
echo "Submitted 02_analyze → job array $JOB2"
PREV_JOB_IDS="$JOB2"

# ---------------------------------------------------------------------------
# Stage 3: Causal patching (CPU, optional)
# ---------------------------------------------------------------------------
if [[ -n "$RUN_PATCH" ]]; then
    PATCH_EXTRA="PATCH_EXPERIMENT=$RUN_PATCH,DISPLACEMENTS=$DISPLACEMENTS,N_DIRECTIONS=$N_DIRECTIONS"
    [[ -n "$REFERENCE_COMPLEX" ]] && PATCH_EXTRA="${PATCH_EXTRA},REFERENCE_COMPLEX=$REFERENCE_COMPLEX"

    JOB3=$(sbatch \
        --parsable \
        --array="$ARRAY_SPEC" \
        --partition="$PARTITION_CPU" \
        "${ACCOUNT_FLAG[@]}" \
        --dependency="afterok:$JOB2" \
        --export="${EXPORT_STR},${PATCH_EXTRA}" \
        "$SLURM_DIR/03_patch.slurm")
    echo "Submitted 03_patch   → job array $JOB3 (experiment: $RUN_PATCH)"
    PREV_JOB_IDS="$JOB3"
fi

# ---------------------------------------------------------------------------
# Stage 4: Aggregate (CPU, single job)
# ---------------------------------------------------------------------------
JOB4=$(sbatch \
    --parsable \
    --partition="$PARTITION_CPU" \
    "${ACCOUNT_FLAG[@]}" \
    --dependency="afterok:$PREV_JOB_IDS" \
    --export="$EXPORT_STR" \
    "$SLURM_DIR/04_aggregate.slurm")
echo "Submitted 04_aggregate → job $JOB4"

echo ""
echo "Pipeline submitted. Track with:"
echo "  squeue -u \$USER"
echo "  tail -f logs/aggregate_${JOB4}.out"
